baseURL      = "https://sudosaket.com/"
languageCode = "en-us"
title        = "Saket Mehta's Blog"

theme = "hugo-journal"

[author]
  name = "Saket Mehta"
  homepage = "https://sudosaket.com/"

[params]
  description = "A blog about software and tech, mostly."
  githubUsername = "sudosaket"
  twitterUsername = "sudosaket"
  tagline = "A blog about software and tech, mostly."
[params.work]
  jobTitle = "Software Engineer"
  company = "AppDynamics"
  companyUrl = "https://www.appdynamics.com/"
# [params.gpg]
#   key = "0x1111111111111111"
#   fingerprint = "0000 0000 0000 0000 0000  0000 0000 0000 0000 0000"
#   link = "https://pgp.mit.edu/pks/lookup?op=get&search=0x1111111111111111"